name: == Deploy to EC2 ==

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: == Deploy to EC2 ==
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_KEY }}
          script: |
            # 예시: 원격 서버 프로젝트 경로로 이동 후 최신 코드 다운로드 & 서비스 재시작
            cd ~/playground
            git pull
            # 서비스 실행/재시작 명령어
            #pip install -r requirements.txt
            # ex) sudo systemctl restart myapp
